### ISSUE TITLE
how to do data normalization for different modalities

### ISSUE THREAD

**Issue by argman** [multimodallearning/DG-TTA#1]
thanks for the code, do you use the default normalization in nnunet ? i cannot see any code about data normalization

**Comment by chr-wei** [comment]
Hey @argman, yes we use the data normalization of nnunet. It is a bit hidden in the code. 
Please refer to the channel name in the dataset.json definition:
https://github.com/multimodallearning/DG-TTA/blob/09df229d66d87383e9ad8c8ab132874cc67f0df1/dg_tta/__resources__/dummy_results/nnUNetTrainer_GIN_MIND_MultiRes__nnUNetPlans__3d_fullres/dataset.json#L112C1-L114C7
